### ISSUE TITLE
Links seem to be broken on 1.18.1

### ISSUE THREAD

**Issue by notquitek3t** [8bitFra/JustIRC#4]
Whenever someone tries to post a link in the chat, all that is shown is `[user] >> https`, and nothing else.

**Comment by notquitek3t** [comment]
Did a bit more of checking, it seems the character `:` just prevents everything after it from showing.

**Comment by 8bitFra** [comment]
Sorry for the delay in replying, however I am aware of this because currently the ":" character is used to separate the message I receive from the irc server. I know it's a really awful solution but currently I don't have time to follow development to implement a cleaner method. I'll probably check it out when I need to upgrade to the new version.

**Comment by 8bitFra** [comment]
Solved in the [latest](https://github.com/8bitFra/JustIRC/releases/tag/v1.0.7) release.
